### ISSUE TITLE
Multiple authors

### ISSUE THREAD

**Issue by vydrin** [maslinych/daba#33]
In Metaeditor, if a file has multiple authors, each author is not stored in the Authors' Database separately. Instead, the set of all the authors of one text is stored as one entry. So, if the text A has one author (ex., Amadu Ture), and the text B has two authors (ex., Amadu Ture & Mamadu Sisoko), Amadu Ture of the text B is not identified with Amadu Ture of the Text A; instead, a new entry, "Amadu Ture & Mamadu Sisoko", is created.
It is necessary to modify the mechanism so that multiple authors' entries were split into individual authors' entries.

**Comment by maslinych** [comment]
Fixed by 914280365411f78b148b0e0d57b751ed9395e54d
